cmake_minimum_required(VERSION 3.8 FATAL_ERROR)
project(openfpm_pdata LANGUAGES C CXX)

if (POLICY CMP0074)
	cmake_policy(SET CMP0074 NEW)
endif()

set(openfpm_VERSION 5.0.0)

if (METIS_FOUND)
	set(DEFINE_HAVE_METIS "#define HAVE_METIS 1")
else()
	message( FATAL_ERROR "Metis is required in order to install OpenFPM" )
endif()

if (PARMETIS_FOUND)
	set(DEFINE_HAVE_PARMETIS "#define HAVE_PARMETIS 1")
else()
	message( FATAL_ERROR "ParMetis is required in order to install OpenFPM")
endif()

set(OPENFPM_PACKAGE_CONFIG_BUILD_DIR
	"${CMAKE_CURRENT_BINARY_DIR}/openfpm_cmake")
set(OPENFPM_CONFIG_VARS_FILE
	"${OPENFPM_PACKAGE_CONFIG_BUILD_DIR}/openfpmConfig-Vars.cmake")
set(OPENFPM_CONFIG_FILE
	"${OPENFPM_PACKAGE_CONFIG_BUILD_DIR}/openfpmConfig.cmake")
file(MAKE_DIRECTORY "${OPENFPM_PACKAGE_CONFIG_BUILD_DIR}")
configure_file(
	"${CMAKE_CURRENT_SOURCE_DIR}/src/cmake/openfpm-config.cmake.in"
	"${OPENFPM_CONFIG_FILE}"
	COPYONLY)

add_subdirectory (src)

unset(CMAKE_OPENFPM_CONFIG_VARS CACHE)
file(READ ${CMAKE_CURRENT_SOURCE_DIR}/src/cmake/openfpmConfig-configure.cmake
	OPENFPM_CONFIG_VARS_CONTENT)
set(OPENFPM_CONFIG_VARS_CONTENT
	"if(NOT OPENFPM_CONFIG_INITIALIZED)\n${OPENFPM_CONFIG_VARS_CONTENT}")
set(OPENFPM_CONFIG_VARS_CONTENT "${OPENFPM_CONFIG_VARS_CONTENT}\nset(OPENFPM_CUDA_ON_BACKEND \"${CUDA_ON_BACKEND}\")")
set(OPENFPM_CONFIG_VARS_CONTENT "${OPENFPM_CONFIG_VARS_CONTENT}\ninclude(CMakeFindDependencyMacro)")
set(OPENFPM_CONFIG_VARS_CONTENT "${OPENFPM_CONFIG_VARS_CONTENT}\nif(NOT Boost_DIR)\n  set(Boost_DIR \"${Boost_DIR}\")\nendif()")
set(OPENFPM_CONFIG_VARS_CONTENT "${OPENFPM_CONFIG_VARS_CONTENT}\nfind_dependency(Boost 1.72 COMPONENTS context fiber filesystem iostreams program_options)")
set(OPENFPM_CONFIG_VARS_CONTENT "${OPENFPM_CONFIG_VARS_CONTENT}\nif(NOT MPI_CXX_COMPILER)\n  set(MPI_CXX_COMPILER \"${MPI_CXX_COMPILER}\")\nendif()")
set(OPENFPM_CONFIG_VARS_CONTENT "${OPENFPM_CONFIG_VARS_CONTENT}\nfind_dependency(MPI COMPONENTS CXX)")
if (CUDA_ON_BACKEND STREQUAL "OpenMP")
	set(OPENFPM_CONFIG_VARS_CONTENT "${OPENFPM_CONFIG_VARS_CONTENT}\nfind_dependency(OpenMP COMPONENTS CXX)")
endif()
if (CUDA_ON_BACKEND STREQUAL "METAL")
	set(OPENFPM_CONFIG_VARS_CONTENT "${OPENFPM_CONFIG_VARS_CONTENT}\nset(OPENFPM_MOLTENVK_HIP_CLANG \"${OPENFPM_MOLTENVK_HIP_CLANG}\")")
	set(OPENFPM_CONFIG_VARS_CONTENT "${OPENFPM_CONFIG_VARS_CONTENT}\nset(OPENFPM_MOLTENVK_LLVM_OPT \"${OPENFPM_MOLTENVK_LLVM_OPT}\")")
	set(OPENFPM_CONFIG_VARS_CONTENT "${OPENFPM_CONFIG_VARS_CONTENT}\nset(OPENFPM_MOLTENVK_LLVM_LINK \"${OPENFPM_MOLTENVK_LLVM_LINK}\")")
	set(OPENFPM_CONFIG_VARS_CONTENT "${OPENFPM_CONFIG_VARS_CONTENT}\nset(OPENFPM_MOLTENVK_CLSPV \"${OPENFPM_MOLTENVK_CLSPV}\")")
	set(OPENFPM_CONFIG_VARS_CONTENT "${OPENFPM_CONFIG_VARS_CONTENT}\nset(OPENFPM_MOLTENVK_SPIRV_VAL \"${OPENFPM_MOLTENVK_SPIRV_VAL}\")")
	set(OPENFPM_CONFIG_VARS_CONTENT "${OPENFPM_CONFIG_VARS_CONTENT}\nset(OPENFPM_CHIPSTAR_ROOT \"${OPENFPM_CHIPSTAR_ROOT}\")")
	set(OPENFPM_CONFIG_VARS_CONTENT "${OPENFPM_CONFIG_VARS_CONTENT}\nset(OPENFPM_CHIPSTAR_GENERATED_INCLUDE \"${OPENFPM_CHIPSTAR_GENERATED_INCLUDE}\")")
	set(OPENFPM_CONFIG_VARS_CONTENT "${OPENFPM_CONFIG_VARS_CONTENT}\ninclude(\"\${CMAKE_CURRENT_LIST_DIR}/../openfpm_devices/cmake/OpenFPMMoltenVK.cmake\")")
endif()
set(OPENFPM_CONFIG_VARS_CONTENT "${OPENFPM_CONFIG_VARS_CONTENT}\ninclude(\"\${CMAKE_CURRENT_LIST_DIR}/../openfpm_devices/cmake/OpenFPMGPU.cmake\")")
set(OPENFPM_CONFIG_VARS_CONTENT
	"${OPENFPM_CONFIG_VARS_CONTENT}\nset(OPENFPM_CONFIG_INITIALIZED TRUE)\nendif()")

set(OPENFPM_NUMERICS_BUILT FALSE)
if (ENABLE_NUMERICS)
	set(OPENFPM_NUMERICS_BUILT TRUE)
endif()
set(OPENFPM_PETSC_FOUND_AT_BUILD FALSE)
if (PETSC_FOUND)
	set(OPENFPM_PETSC_FOUND_AT_BUILD TRUE)
endif()
configure_file(
	${CMAKE_CURRENT_SOURCE_DIR}/src/cmake/openfpm-config-components.cmake.in
	${OPENFPM_PACKAGE_CONFIG_BUILD_DIR}/openfpmConfig-components.cmake
	@ONLY)
file(READ
	${OPENFPM_PACKAGE_CONFIG_BUILD_DIR}/openfpmConfig-components.cmake
	OPENFPM_COMPONENT_CONFIG)
set(OPENFPM_CONFIG_VARS_CONTENT
	"${OPENFPM_CONFIG_VARS_CONTENT}\n${OPENFPM_COMPONENT_CONFIG}")
file(WRITE "${OPENFPM_CONFIG_VARS_FILE}" "${OPENFPM_CONFIG_VARS_CONTENT}")

get_directory_property(hasParent PARENT_DIRECTORY)
if(hasParent)
	set(DEFINE_HAVE_METIS ${DEFINE_HAVE_METIS} CACHE INTERNAL "")
	set(DEFINE_HAVE_PARMETIS ${DEFINE_HAVE_PARMETIS} CACHE INTERNAL "")
endif()
