cmake_minimum_required(VERSION 3.8 FATAL_ERROR)
project(openfpm_pdata LANGUAGES C CXX)

if (POLICY CMP0074)
	cmake_policy(SET CMP0074 NEW)
endif()

set(openfpm_VERSION 5.0.0)

if (METIS_FOUND)
	set(DEFINE_HAVE_METIS "#define HAVE_METIS 1")
else()
	message( FATAL_ERROR "Metis is required in order to install OpenFPM" )
endif()

if (PARMETIS_FOUND)
	set(DEFINE_HAVE_PARMETIS "#define HAVE_PARMETIS 1")
else()
	message( FATAL_ERROR "ParMetis is required in order to install OpenFPM")
endif()

add_subdirectory (src)

file(READ ${CMAKE_CURRENT_SOURCE_DIR}/src/cmake/openfpmConfig-configure.cmake CMAKE_OPENFPM_CONFIG_VARS)
set(CMAKE_OPENFPM_CONFIG_VARS
	"if(NOT OPENFPM_CONFIG_INITIALIZED)\n${CMAKE_OPENFPM_CONFIG_VARS}")
set(CMAKE_OPENFPM_CONFIG_VARS "${CMAKE_OPENFPM_CONFIG_VARS}\nset(OPENFPM_CUDA_ON_BACKEND \"${CUDA_ON_BACKEND}\")")
set(CMAKE_OPENFPM_CONFIG_VARS "${CMAKE_OPENFPM_CONFIG_VARS}\ninclude(CMakeFindDependencyMacro)")
set(CMAKE_OPENFPM_CONFIG_VARS "${CMAKE_OPENFPM_CONFIG_VARS}\nif(NOT Boost_DIR)\n  set(Boost_DIR \"${Boost_DIR}\")\nendif()")
set(CMAKE_OPENFPM_CONFIG_VARS "${CMAKE_OPENFPM_CONFIG_VARS}\nfind_dependency(Boost 1.72 COMPONENTS context fiber filesystem iostreams program_options)")
set(CMAKE_OPENFPM_CONFIG_VARS "${CMAKE_OPENFPM_CONFIG_VARS}\nif(NOT MPI_CXX_COMPILER)\n  set(MPI_CXX_COMPILER \"${MPI_CXX_COMPILER}\")\nendif()")
set(CMAKE_OPENFPM_CONFIG_VARS "${CMAKE_OPENFPM_CONFIG_VARS}\nfind_dependency(MPI COMPONENTS CXX)")
if (CUDA_ON_BACKEND STREQUAL "OpenMP")
	set(CMAKE_OPENFPM_CONFIG_VARS "${CMAKE_OPENFPM_CONFIG_VARS}\nfind_dependency(OpenMP COMPONENTS CXX)")
endif()
if (CUDA_ON_BACKEND STREQUAL "METAL")
	set(CMAKE_OPENFPM_CONFIG_VARS "${CMAKE_OPENFPM_CONFIG_VARS}\nset(OPENFPM_MOLTENVK_HIP_CLANG \"${OPENFPM_MOLTENVK_HIP_CLANG}\")")
	set(CMAKE_OPENFPM_CONFIG_VARS "${CMAKE_OPENFPM_CONFIG_VARS}\nset(OPENFPM_MOLTENVK_LLVM_OPT \"${OPENFPM_MOLTENVK_LLVM_OPT}\")")
	set(CMAKE_OPENFPM_CONFIG_VARS "${CMAKE_OPENFPM_CONFIG_VARS}\nset(OPENFPM_MOLTENVK_LLVM_LINK \"${OPENFPM_MOLTENVK_LLVM_LINK}\")")
	set(CMAKE_OPENFPM_CONFIG_VARS "${CMAKE_OPENFPM_CONFIG_VARS}\nset(OPENFPM_MOLTENVK_CLSPV \"${OPENFPM_MOLTENVK_CLSPV}\")")
	set(CMAKE_OPENFPM_CONFIG_VARS "${CMAKE_OPENFPM_CONFIG_VARS}\nset(OPENFPM_MOLTENVK_SPIRV_VAL \"${OPENFPM_MOLTENVK_SPIRV_VAL}\")")
	set(CMAKE_OPENFPM_CONFIG_VARS "${CMAKE_OPENFPM_CONFIG_VARS}\nset(OPENFPM_CHIPSTAR_ROOT \"${OPENFPM_CHIPSTAR_ROOT}\")")
	set(CMAKE_OPENFPM_CONFIG_VARS "${CMAKE_OPENFPM_CONFIG_VARS}\nset(OPENFPM_CHIPSTAR_GENERATED_INCLUDE \"${OPENFPM_CHIPSTAR_GENERATED_INCLUDE}\")")
	set(CMAKE_OPENFPM_CONFIG_VARS "${CMAKE_OPENFPM_CONFIG_VARS}\ninclude(\"\${CMAKE_CURRENT_LIST_DIR}/../openfpm_devices/cmake/OpenFPMMoltenVK.cmake\")")
endif()
set(CMAKE_OPENFPM_CONFIG_VARS "${CMAKE_OPENFPM_CONFIG_VARS}\ninclude(\"\${CMAKE_CURRENT_LIST_DIR}/../openfpm_devices/cmake/OpenFPMGPU.cmake\")")
set(CMAKE_OPENFPM_CONFIG_VARS
	"${CMAKE_OPENFPM_CONFIG_VARS}\nset(OPENFPM_CONFIG_INITIALIZED TRUE)\nendif()")

set(OPENFPM_NUMERICS_BUILT FALSE)
if (ENABLE_NUMERICS)
	set(OPENFPM_NUMERICS_BUILT TRUE)
endif()
set(OPENFPM_PETSC_FOUND_AT_BUILD FALSE)
if (PETSC_FOUND)
	set(OPENFPM_PETSC_FOUND_AT_BUILD TRUE)
endif()
configure_file(
	${CMAKE_CURRENT_SOURCE_DIR}/src/cmake/openfpm-config-components.cmake.in
	${CMAKE_CURRENT_BINARY_DIR}/openfpmConfig-components.cmake
	@ONLY)
file(READ ${CMAKE_CURRENT_BINARY_DIR}/openfpmConfig-components.cmake
	OPENFPM_COMPONENT_CONFIG)
set(CMAKE_OPENFPM_CONFIG_VARS
	"${CMAKE_OPENFPM_CONFIG_VARS}\n${OPENFPM_COMPONENT_CONFIG}")
file(WRITE ${CMAKE_CURRENT_SOURCE_DIR}/src/cmake/openfpmConfig-Vars.cmake "${CMAKE_OPENFPM_CONFIG_VARS}")

get_directory_property(hasParent PARENT_DIRECTORY)
if(hasParent)
	set(DEFINE_HAVE_METIS ${DEFINE_HAVE_METIS} CACHE INTERNAL "")
	set(DEFINE_HAVE_PARMETIS ${DEFINE_HAVE_PARMETIS} CACHE INTERNAL "")
endif()
